version: '3.8'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pre_order
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    restart: always

volumes:
  db: