version: '3.8'

services:
  db_pre_order_user:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pre_order_user
    ports:
      - "3306:3306"
    volumes:
      - db_user:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - user_network

  db_pre_order_item:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pre_order_item
    ports:
      - "3307:3306"
    volumes:
      - db_item:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  db_pre_order_order:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pre_order_order
    ports:
      - "3308:3306"
    volumes:
      - db_order:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  db_pre_order_payment:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pre_order_payment
    ports:
      - "3309:3306"
    volumes:
      - db_payment:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  db_pre_order_stock:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pre_order_stock
    ports:
      - "3310:3306"
    volumes:
      - db_stock:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - stock_network

  redis_user:
    hostname: redis_user
    container_name: redis_user
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - user_network

  redis_stock:
    hostname: redis_stock
    container_name: redis_stock
    image: redis:6
    ports:
      - "6380:6379"
    networks:
      - stock_network

volumes:
  db_user:
  db_item:
  db_order:
  db_payment:
  db_stock:

networks:
  user_network:
  stock_network:

