version: '3.8'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pre_order_order
    ports:
      - "3308:3306"
    volumes:
      - db_order:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - hanghae_network

volumes:
  db_order:

networks:
  hanghae_network:
